### ISSUE TITLE
linter: Improve mypy configuration

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#116]
Currently, mypy is not very well configured.

This is the new configuration proposed:

```toml
[tool.mypy]
python_version = "3.8"
check_untyped_defs = true
strict = true
ignore_missing_imports = true
warn_unused_ignores = true
warn_redundant_casts = true
warn_unused_configs = true
show_error_codes = true
exclude = ["scripts/"]
```
