### ISSUE TITLE
Explicit group naming for tasks to remove default group mechanism

### ISSUE THREAD

**Issue by ansh808s** [osl-incubator/makim#168]
currently makim allows tasks to be defined without explicitly specifying the group name, defaulting to the first group in the configuration, this can cause confusion and unexpected results when executing tasks.

These both config gives same output which is confusing

```yaml
groups:
  test:
    tasks:
      test-echo:
        run: echo "Basic echo test successful"
      test-all:
        hooks:
          pre-run:
            - task: test-echo
```

```yaml
groups:
  test:
    tasks:
      test-echo:
        run: echo "Basic echo test successful"
      test-all:
        hooks:
          pre-run:
            - task: test.test-echo

```
