### ISSUE TITLE
Validate task conditional

### ISSUE THREAD

**Issue by ansh808s** [osl-incubator/makim#172]
currently these both config files gives the same output
```yaml
hooks:
  pre-run:
    - task: build.clean
      if: ${{ args.cleans }}
```
and

```yaml
hooks:
  pre-run:
    - task: build.clean
      if: ${{ helloworld}}
```
we want to validate the jinja in the `if` conditional to execute hook accordingly
