### ISSUE TITLE
Implement retry mechanism for tasks

### ISSUE THREAD

**Issue by ansh808s** [osl-incubator/makim#174]
Implement a retry mechanism example
```yaml
tasks:
  retry-task:
    help: "A task that might fail"
    run: curl http://retry-api.com
    retry:
      count: 3
```
