### ISSUE TITLE
Add to the target an option for success and failure

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#18]
It would be nice if the target has an option for success or failure .. so we can have alternatives commands for both flows.

**Comment by xmnlab** [comment]
example:

```
version: 1.0.0
groups:
  - name: default
    env-file: .env
    targets:
      clean:
        help: Use this target to clean up temporary files
        args:
          all:
            type: bool
            action: store_true
            help: Remove all files that are tracked by git
        run: |
          echo "remove file X"
        success: echo "ok"
        failure: echo "false"
      build:
        help: Build the program
        args:
          clean:
            type: bool
            action: store_true
            help: if not set, the clean dependency will not be triggered.
        dependencies:
          - target: clean
            if: \${\{ args.clean == true \}\}
        run: |
          echo "build file x"
          echo "build file y"
```
