### ISSUE TITLE
Change groups items from list to dict

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#20]
Currently, the yaml file looks like this:

```yaml

version: 1.0.0
groups:
  - name: default
    targets:
      clean:
        help: Clean unnecessary temporary files
        run: |
          rm -fr build/
          rm -fr dist/
          rm -fr .eggs/
          find . -name '*.egg-info' -exec rm -fr {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name
          find . -name '__pycache__' -exec rm -fr '*.pyo' -exec rm -f {} +
          find . -name '*~' -exec rm -f {} +{} +
          rm -f .coverage
          rm -fr htmlcov/
          rm -fr .pytest_cache
  - name: docs
    env-file: .env
    targets:
      build:
        help: Build documentation
        run: |
          mkdocs build --config-file docs/mkdocs.yaml
```

and now it should look like this:

```yaml

version: 1.0.0
groups:
  default:
    targets:
      clean:
        help: Clean unnecessary temporary files
        run: |
          rm -fr build/
          rm -fr dist/
          rm -fr .eggs/
          find . -name '*.egg-info' -exec rm -fr {} +
          find . -name '*.egg' -exec rm -f {} +
          find . -name '*.pyc' -exec rm -f {} +
          find . -name
          find . -name '__pycache__' -exec rm -fr '*.pyo' -exec rm -f {} +
          find . -name '*~' -exec rm -f {} +{} +
          rm -f .coverage
          rm -fr htmlcov/
          rm -fr .pytest_cache

  docs:
    env-file: .env
    targets:
      build:
        help: Build documentation
        run: |
          mkdocs build --config-file docs/mkdocs.yaml

```
