### ISSUE TITLE
Add support for pipelines

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#26]
In order to add support for pipelines, we could add a new entry in the root of the file for pipelines .. and create pipelines using any of the targets. Example:

```yaml
version: 1.0.0
groups:
  main:
    env-file: .env
    targets:
      read:
        help: Read file
        args:
          filepath:
            type: string
            default:
        run: cat {{ args.filepath }}
      count:
        help:  Counts the number of lines in the input.
        run: wc -l

pipelines:
  count-lines-myfile:
    help: 
    tasks:
      - target: main.read
        args:
          filepath: /tmp/myfile.txt
      - target: main.count
```

makim could have an option to visualize the graph of the pipelines, maybe using `asciinet`. Example of a CLI call: 

```
$ makim pipeline run count-lines-myfile
$ makim pipeline show count-lines-myfile
```

**Comment by Krishna9588** [comment]
I understand this is just the skeleton of what we are planning to develop, but here we can add error handling in case, the program doesn't run properly and accepts dynamic input for file path for improved flexibility.

**Comment by xmnlab** [comment]
hi @Krishna9588 , that is right. 
also it would probably need to keep the logs in a database (maybe sqlite?)
we should discuss more about that though.

**Comment by xmnlab** [comment]
for the pipelines, maybe we could use as a backend celery.

This is just an example of yaml that implements a structure similar to celery:

```yaml

pipeline:
  config:
    mycelery:
      broker-url: ${{ REDIS_URL }}
      result-url: ${{ REDIS_URL }}

    workflows:
      myworkflow:
        config: mycelery
        dag: 
          - group1.op1 >> [group1.op2, group1.op3]
          - group1.op2 >> group1.op4
          - group1.op3 >> group1.op5
          - [group1.op4, group1.op5] >> group1.op6
```

Please reference to airflow for more details: https://airflow.apache.org/docs/apache-airflow/1.10.12/concepts.html#bitshift-composition
