### ISSUE TITLE
Add a step in the main CI workflow that checks the PR title according to semantic-release

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#31]
example:

```
      - name: Semantic Release PR Title Check
        uses: osl-incubator/semantic-release-pr-title-check@v1.4.1
        if: success() || failure()
        with:
          convention-name: conventionalcommits
```

ref: https://github.com/osl-incubator/cookiecutter-python/blob/main/.github/workflows/main.yaml#L44
