### ISSUE TITLE
Add an option for targets to specify a log file

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#38]
It would be nice to have an option to specify a log for for a target. also, it would be nice to define the level for the log (stdout, stderr, or both). For example:

```yaml

groups:
  mygroup:
    targets:
       mytarget:
         log:
           path: /tmp/log.txt
           level: err  # err, out, both
```
