### ISSUE TITLE
Add support for interactive arguments

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#42]
Add support for interactive arguments using "typer" library

We could create a new item inside the target data, maybe config, and specify there a configuration for args with interactive mode, for example:

```yaml
...
groups:
  group1:
    tasks:
      task1:
        args:
          password:
            type: string
            interactive: true
```
