### ISSUE TITLE
Add a parameter working-directory to global, group and target scope

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#48]
Add an parameter working-directory to global, group and target scope, this will be applied just before the `run` block be executed.

the working-directory used by a target would applied on top of the working-directory defined by the group .. and it would be applied on top of the working-directory defined on the global scope.

Example

```yaml
version: 1.0.0
working-directory: /opt/services  # /opt/services
groups:
  default:
    env-file: .env
    working-directory: service-default-1  # relative: /opt/services/service-default-1
    targets:
      target1:
        help: Use this target to clean up temporary files
        working-directory: scripts/myfolder  # relative: /opt/services/service-default-1/scripts/myfolder
        run: |
          echo "remove file X"
      target2:
        help: Use this target to clean up temporary files
        working-directory: /tmp  # absolute path
        run: |
          echo "remove file Y"
```

It should work for absolute or relative paths.

Some references:

# 1
https://github.com/osl-incubator/makim/blob/e14b963927abea87a08bc871aad5b7df430fea39/makim/makim.py#L83
where the command is executed. you can use the parameter `_cwd`: https://sh.readthedocs.io/en/latest/sections/special_arguments.html#cwd

# 2

you can create a variable here for `working_directory`: https://github.com/osl-incubator/makim/blob/e14b963927abea87a08bc871aad5b7df430fea39/makim/makim.py#L61

working_directory attribute should be of type `Path` (from pathlib import Path)

# 3

Create a method called `_load_working_directory`, and follow the same pattern used by `_load_shell_app` and replicate that for working_directory
