### ISSUE TITLE
Add an additional option for specifying a custom flag for prompt command

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#55]
Currently, makim can use any prompts/shells/interpreters that support `-c` for reading the command.

we need to support an option for custom flag for command.

example:

```
version: 1.0
env-file: .env
shell: php
shell-flag: "-f"
groups:
  php:
    targets:
      print:
        help: print 1
        run: |
           print('1')
```

the `shell-flag` should be applied from the 3 scopes when necessary: global, group or target
the function/property to be changed is `shell_args`
