### ISSUE TITLE
docs: Fix old style documentation: replace list of groups by a dictionary

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#56]
example:

this should be replaced by 

```
version: 1.0.0
groups:
  - name: default
    env-file: .env
```

```
version: 1.0.0
groups:
  default:
    env-file: .env
```
