### ISSUE TITLE
Change from dependencies to hooks

### ISSUE THREAD

**Issue by xmnlab** [osl-incubator/makim#75]
Currently we use the attribute `dependencies` to define dependencies among targets.

Although it works fine, but it is just a pre-run (setup) hook, and we would need to add support for post-run (teardown) hook as well.

Example:

```yaml

version: 1.0
env-file: .env
groups:
  main:
    tasks:
      target1:
        help: target1
        run: echo "target 1"
      target2:
        help: target2
        run: echo "target 2"

  build:
    targets:
      clean:
        help: target clean
        hooks:
          pre-run: 
            - task: main.target1
          post-run:
            - task: main.target2
        run: echo "target clean"
```

**Comment by xmnlab** [comment]
change in the .makim.yaml layout

current state:

```yaml
...

  build:
    targets:
      clean:
        help: target clean
        dependencies:
          - task: main.target1
            if: ${{ 1 == 1 }}
        run: echo "target clean"
```

```yaml
...

  build:
    targets:
      clean:
        help: target clean
        hooks:
          pre-run: 
            - task: main.target1
              if: ${{ 1 == 1 }}
        run: echo "target clean"
```

example with post-run

```yaml
...

  build:
    targets:
      clean:
        help: target clean
        hooks:
          pre-run: 
            - task: main.target1
              if: ${{ 1 == 1 }}
          post-run:
            - task: main.target2
              if: ${{ 1 == 1 }}
        run: echo "target clean"
```
